//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.17 at 05:32:18 PM CST 
//


package com.rr.study.j2se.xml.jaxb.shool.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rr.study.j2se.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _School_QNAME = new QName("http://www.rr.com/study/j2se/xml/jaxb/school", "School");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rr.study.j2se.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchoolType }
     * 
     */
    public SchoolType createSchoolType() {
        return new SchoolType();
    }

    /**
     * Create an instance of {@link GradeType }
     * 
     */
    public GradeType createGradeType() {
        return new GradeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchoolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rr.com/study/j2se/xml/jaxb/school", name = "School")
    public JAXBElement<SchoolType> createSchool(SchoolType value) {
        return new JAXBElement<SchoolType>(_School_QNAME, SchoolType.class, null, value);
    }

}
